### ISSUE TITLE
Add *Weapons of Math Destruction*

### ISSUE THREAD

**Issue by dit7ya** [chobeat/awesome-critical-tech-reading-list#2]
A quick introduction to the book.

https://www.youtube.com/watch?v=_2u_eHHzRto

The book.

https://en.wikipedia.org/wiki/Weapons_of_Math_Destruction

**Comment by chobeat** [comment]
Uh, interesting. I've heard about the book before but I didn't read it and I don't think I'm that interested right now, but I think it would be a good addition to the list. I will go over some reviews and add it.

**Comment by chobeat** [comment]
If you like to spread this book, here there's an even more compact introduction: https://aeon.co/videos/algorithms-are-opinions-not-truth-machines-and-demand-the-application-of-ethics
